# Generated by Django 5.0.11 on 2025-07-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_consumptiondatapoint_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="description",
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="emergency_priority",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Muy Baja"),
                    (2, "Baja"),
                    (3, "Media"),
                    (4, "Alta"),
                    (5, "Muy Alta"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="ideal_count",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
