# Generated by Django 5.0.11 on 2025-07-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_remove_productcategory_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="emergency_priority",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Muy Baja"),
                    (2, "Baja"),
                    (3, "Media"),
                    (4, "Alta"),
                    (5, "Muy Alta"),
                ],
                default=3,
                help_text="Priority level during emergency situations",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="ideal_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Recommended inventory level"
            ),
        ),
    ]
